### PR TITLE
MRG: fix to viz test error in Python 3

### PR DESCRIPTION
**Pull request by matthew-brett**
Fix by Bertrand.

I (MB) added some refactoring and tests.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Any comments here?  Bertrand?

**Comment by matthew-brett** [comment]
Could I humbly ask for a quick review here?   I hope to get us into a state of all tests passing soon, so we can get ready for a release.

**Comment by bthirion** [comment]
LGTM. Since travis is green, you can proceed with merge.

**Comment by matthew-brett** [comment]
Thanks - merging

**Pull request merged**
