### PR TITLE
MRG: Tried to fix failing tests due to numerical issues

### PR DESCRIPTION
**Pull request by bthirion**
Trying to solve the Travis errors. I don't reproduce them on my box, which makes the whole thing a bit complicated. I am assuming that these are simply numerical issues.

Disclaimer: For some reason, I don't get Travis output atm.

### CODE REVIEW

**Comment by bthirion** [comment]
Apparently Python 2.6, 2.7 and 3.2 issues are fixed. The remaining ones are related to cython stuff and should probably be handled separately.

**Comment by matthew-brett** [comment]
Bertrand - I've added your viz fix in https://github.com/nipy/nipy/pull/345

Can I close this PR in favor of #345 now we've merged #339 ?

**Comment by bthirion** [comment]
Hi Matthew,

Please do.

**Comment by matthew-brett** [comment]
Thanks Bertrand - closing.

**Pull request closed without merging**
