### PR TITLE
MRG: refactor scripts into entry points

### PR DESCRIPTION
**Pull request by matthew-brett**
Now we depend on setuptools, use entry points for scripts.

Thanks @effigies for the suggestion.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Any chance of a review here?  Once merged I'm happy to rebase / merge the Python 3 shebangs for the examples at #469 .

**Comment by effigies** [comment]
Looks like coverage barely changed, but what about the script runner tests?

https://github.com/nipy/nipy/blob/master/nipy/tests/scriptrunner.py

I'll try to have a more detailed look today if nobody gets to it first.

**Comment by effigies** [comment]
All of the changes up to this point look good. And it seems that the script runner tests tolerate the shift in Linux, but [not in Windows](https://ci.appveyor.com/project/matthew-brett/nipy/builds/37890062/job/lewb8wx8wepcaf54#L625).

**Comment by matthew-brett** [comment]
OK - I believe I've tracked down the Windows script errors now : https://ci.appveyor.com/project/matthew-brett/nipy/builds/37929980

**Review by effigies — APPROVED** [review]
LGTM.

**Comment by matthew-brett** [comment]
Thanks Chris.

**Pull request merged**
