### PR TITLE
BF: make histogram bins integer for numpy 1.10

### PR DESCRIPTION
**Pull request by matthew-brett**
Numpy 1.10 seems to need an integer input to np.histogram.

Probably fixes gh-369.

I would be happy of a quick review.

### CODE REVIEW

**Comment by effigies** [comment]
Looking at numpy/numpy#6469, it looks like it was rounding down before. Is this an explicit decision to round up? For consistent behavior across versions, I'd probably use integer division:

    bins = max(10, (self.x.max() - self.x.min()) // step)

To compare, another `np.histogram` call in this file [coerces to `int`](https://github.com/matthew-brett/nipy/blob/numpy-1.10-fix/nipy/algorithms/statistics/empirical_pvalue.py#L350). And another one looks like it [needs coercing/rounding](https://github.com/matthew-brett/nipy/blob/numpy-1.10-fix/nipy/algorithms/statistics/empirical_pvalue.py#L582). A little surprised that's not causing test failures.

**Comment by matthew-brett** [comment]
Thanks for looking at this.  I made the // change you suggested.

The other np.histogram instance you found, I think is passing a vector of bin positions, so these do not have to be integers.

**Comment by effigies** [comment]
Makes sense. CI error seems unrelated, so LGTM.

**Comment by matthew-brett** [comment]
Thanks again for the review - in it goes.

**Pull request merged**
