### PR TITLE
MRG: temporarily revert lapack refactor for testing

### PR DESCRIPTION
**Pull request by matthew-brett**
Lapack refactor increases our scipy dependency to 0.13 (see gh-344) and causes
some build errors (see gh-342).

Revert for now, so we can reconsider how best to fix up gh-328.

As discussed in gh-344.

### CODE REVIEW

**Comment by matthew-brett** [comment]
OK - I think this one is ready now - Alexis - do you have time to take a look?

**Comment by matthew-brett** [comment]
@alexis-roche - would you mind having a look at this one?   It's the last big piece in fixing the builds.

**Comment by matthew-brett** [comment]
If anyone is reviewing this - it is best reviewed by commit, not via the "Files changed" interface.

The first commit 9d83fc3 just reverts Alexis' previous changes to make the code independent of an external BLAS  / LAPACK library, so doesn't need a review (other than maybe thinking about the policy of reverting it, discussed in the intro at the top of this PR).

The second commit d9a2983 is a tiny Makefile change to help compile the Cython .pyx files.

The third commit d5b81f6 is just a rebuild of a .c file from the .pyx file and doesn't need review.

The fourth commit cd595cf does need some review, because it's a change in the way of sharing the Numpy C API table.  This commit doesn't contain the changes from the .c files generated from the .pyx changes, to help with review.

The last commit 14e5332 is just the generated .c file changes, and doesn't need review.

Thanks - sorry this one is a little annoying to review.

**Comment by effigies** [comment]
I had a look. Second and fourth commits look good.

Remaining errors seem to be #258 related?

**Comment by matthew-brett** [comment]
Yes, the last errors should be fixed in nipy master (which has the fix for #258 .   I tested an integration branch here (current master with this PR): https://travis-ci.org/matthew-brett/nipy/builds/77797820

**Comment by effigies** [comment]
Cool. Looks good, then, noting that I didn't try to look at the reversion commit.

**Comment by matthew-brett** [comment]
Thanks for the review.

Will hold off merge until Monday hoping that Alexis has time to take a look.

**Comment by alexis-roche** [comment]
Yes, sorry I am off for the week-end with just a smartphone. I'll have a
look first thing Monday morning. Cheers.

**Comment by alexis-roche** [comment]
OK, I see that it's reverted to the point where "lapack lite" is compiled by default, so at least no linking with a system lapack is attempted (this can only be changed by manually editing `nipy/labs/setup.py`). It works on my box. 

I think we here have a robust solution to bind the required lapack/blas routines, one that works with many scipy and python versions. It would in theory be more elegant to use the C function pointers exposed by the scipy API, however in practice it would be a mess if we jointly consider scipy < 0.13 and python > 2.7. My gut feeling is to stick to the pragmatic "lapack lite" approach, given that nipy is becoming obsolete anyway.

**Comment by matthew-brett** [comment]
So I think you're saying you think this one is good to merge?

Should we provide a configuration option to link to optimized lapack if available (instead of requiring an edit to `nipy.labs.setup.py`)?

**Comment by alexis-roche** [comment]
Yes, sorry, good to merge. I thought about providing a config option, but didn't see a standard way to do this at the time. What we want to do is reset the `WANT_LAPACK_LINKING` variable in `nipy.labs.setup.py`, which defaults to False.

**Comment by matthew-brett** [comment]
OK - let's merge for now, and I'll have a look to see if I can find some configuration option in shortish exploration time.

**Comment by matthew-brett** [comment]
Here's my attempt at the configuration stuff : https://github.com/nipy/nipy/pull/352

**Pull request merged**
