### PR TITLE
Reggy affine

### PR DESCRIPTION
**Pull request by arokem**
I think I might have misplaced the translations for the affine in the previous PR. Just for my curiosity: would anyone care to enlighten me as to why these things have 5x5 affines?

### CODE REVIEW

**Comment by matthew-brett** [comment]
Sorry for the crazy long time to get to this one.

I think the right way to solve this is to use `nipy.save_image` - see https://github.com/matthew-brett/nipy/commit/7c696a5d0dab634deccc543da687c80e55e46ff8

Does that look right to you?   Can you play with the output to check?

**Comment by matthew-brett** [comment]
@arokem - do you have time to look at this one?

**Comment by arokem** [comment]
Not today

**Comment by arokem** [comment]
More precisely: this looks about right to me, but I will not have time to
experiment with this before October 12th. In particular, I don't quite
remember what data analysis triggered this fix, so I will have to dig up
the data I was probably using this with and investigate.

**Comment by matthew-brett** [comment]
I think we're going to release before then, do you think I should release with this fix?

**Comment by arokem** [comment]
Definitely with one of the fixes, probably yours - I probably would've gone
with that, if I was more nipy-savvy.

**Comment by matthew-brett** [comment]
Ok - I hope my fix is right then.

**Comment by matthew-brett** [comment]
Ariel - would you mind casting a quick eye over : https://github.com/nipy/nipy/pull/363? If you agree then we can close this one and get the fix merged soon.

**Pull request closed without merging**
