### PR TITLE
Capitalized constants

### PR DESCRIPTION
**Pull request by TheChymera**
Addresses #411

### CODE REVIEW

**Comment by matthew-brett** [comment]
Excellent - thanks for doing that.

**Comment by matthew-brett** [comment]
@nibotmi r+

**Comment by TheChymera** [comment]
@matthew-brett one unrelated question: I header nipy is being discontinued? Is that true? What happens to all the nice native-python preprocessing functions when it does?

**Comment by matthew-brett** [comment]
The general plan is to keep nipy maintained for the next five years or so, but more active development of various parts has shifted to: 

1) registration : https://github.com/nipy/nireg (although it looks like development is a bit slow);
2) one of the two statistical interfaces : https://github.com/nistats/nistats

My provisional plan is to start development on something that might be called nipy2, with a changed interface, fixing some of the painful parts of the current nipy interface.  At that point it would be a good idea to import from those modules, if they are in good shape.

**Comment by matthew-brett** [comment]
Sorry - I should also say that modern versions of the visualization stuff are in https://github.com/nilearn/nilearn

**Pull request merged**
