### PR TITLE
Numpy 20 fixes

### PR DESCRIPTION
**Pull request by matthew-brett**
Working on build / compile and test for Numpy 2.0.

### CODE REVIEW

**Comment by matthew-brett** [comment]
Currently blocked by multiple regular but not deterministic segmentation faults, that seem to be most commonly from `fffpy_multi_iterator_delete` or elsewhere in the `fffpy_multi_iterator` stuff.

**Comment by matthew-brett** [comment]
@alexis-roche - do you have any time to have a look at what's going on here with `fff` and Numpy 2.0 crashes?

Procedure is:

```bash
virtualenv nipy-env
. ./nipy-env/bin/activate
git clone https://github.com/matthew-brett/nipy
cd nipy
git checkout numpy-20-fixes
pip install meson-python ninja cython numpy pytest
pip install --no-build-isolation --editable .
pytest nipy/labs/bindings/tests/test_numpy.py
```

If it doesn't segfault first time, try running the `pytest` line a few times.

In case it's useful - Numpy 2.0 changes : https://numpy.org/doc/stable//numpy_2_0_migration_guide.html

**Comment by effigies** [comment]
I'm not getting segfaults, but I am getting:

```
corrupted size vs. prev_size
[1]    769785 IOT instruction (core dumped)  pytest -sv nipy/labs/bindings/tests/test_numpy.py
```

```
double free or corruption (out)
[1]    769607 IOT instruction (core dumped)  pytest -sv nipy/labs/bindings/tests/test_numpy.py
```

I don't have any insights into what's causing this.

**Comment by effigies** [comment]
Given Py3.8 is end-of-life next week, might make more sense to just remove support and end testing on it.

**Comment by matthew-brett** [comment]
Good call - dropped.  Tests passing now.

**Comment by matthew-brett** [comment]
Ah - that turns out to be because Python 3.8 pulls in Numpy < 2, which is the actual problem.

**Review by effigies — APPROVED** [review]
LGTM

**Comment by matthew-brett** [comment]
Numpy issue with description, discussioon, resolution of segfault: https://github.com/numpy/numpy/issues/26765

**Pull request merged**
