### PR TITLE
RF: rename variables in ROI selection loops

### PR DESCRIPTION
**Pull request by matthew-brett**
Rename variables for clarity, as proposed in
https://github.com/nipy/nipy/pull/422

### CODE REVIEW

**Comment by matthew-brett** [comment]
By the way, I think https://github.com/nipy/nipy/blob/master/nipy/labs/spatial_models/mroi.py#L689 must be wrong - the `self` variable will get rebound, and so have no effect on the `self` in the method signature.  You'd need to set the properties / attributes of `self` directly.

**Comment by matthew-brett** [comment]
I added a fix and test for the select_roi bug.

**Comment by matthew-brett** [comment]
@VirgileFritsch - any comment here?

**Comment by VirgileFritsch** [comment]
That's fine. Thank you Matthew :)

**Comment by matthew-brett** [comment]
Thanks - in it goes.

**Pull request merged**
