### PR TITLE
test_olsR: use assert_array_almost_equal instead

### PR DESCRIPTION
**Pull request by ignatenkobrain**
due to bug in numpy

Related: https://github.com/numpy/numpy/issues/5200

### CODE REVIEW

**Comment by bthirion** [comment]
Dear Igor,

     The fix sounds right, but beware that nipy contains lots of dead 
code and is actually no longer developed.
     Depending on your need, you might want to look at other projects.
     Best,

Bertrand Thirion

**Comment by matthew-brett** [comment]
Great - thanks for doing this.  Looks good to me.

I will keep nipy in maintenance mode for at least another three years, probably five.

The code that you're testing here is I think already in `nistats` and will soon be in another package based on Jonathan Taylor's work for the current FMRI statistics stuff, and I can keep track of the correspondence for the second package - I guess Bertrand will be doing the same for `nistats`.

**Comment by ignatenkobrain** [comment]
I'm packaging all projects related, so I'm working on packaging nistats also. There are problem with non compatible with new version of nilearn, but I hope this will be fixed soon.

**Comment by bthirion** [comment]
It will, for sure. We were waiting for the next Nilearn release, to be compatible with release versions.

**Pull request merged**
