### PR TITLE
shebang to python3 not python

### PR DESCRIPTION
**Pull request by yarikoptic**
As on some platforms python might still be pointing to good old
python2 and I would expect python3 present - use it in shebang
to signify need for python3

### CODE REVIEW

**Comment by effigies** [comment]
Last I knew Nipy still claimed Py2 support. Should the next release do away with that?

**Comment by matthew-brett** [comment]
Yes, that seems a little extreme.   I personally alias python to python3 - wouldn't we expect most of our users to do something like that, if that's what they wanted?

**Comment by yarikoptic** [comment]
Are you suggesting to include into installation instructions necessity to alias python to python 3? (Bash alias isn't enough BTW for shebangs afaik, so need to be a symlink... System wide?)

What are you gaining by keeping ability to run with EOLed python 2?

**Comment by yarikoptic** [comment]
> Last I knew Nipy still claimed Py2 support. Should the next release do away with that?

It could as well support python 1 . Here is the question with what python to run scripts on a system after installation. Debian got rid of python (2). We can keep the patch for Debian package but then likely people wouldn't be able to run them if installed otherwise

**Comment by effigies** [comment]
So Debian now has `python3` but not `python`? Part of the point of writing scripts that supported both Python 2 and 3 was so that you didn't have to care what the local Python was. Scripts that depended on a particular version could put `python2` or `python3`.

I'm for dropping Python 2, but I'd rather do it as a deliberate act, e.g., set it in the classifiers and set `python_requires` so that Python 2 installations at least have a chance of not installing something that is guaranteed to break.

**Comment by matthew-brett** [comment]
I think #473 is a duplicate.

Is this a Debian requirement / default?   I don't care enough about it to resist, if it is.

**Comment by mr-c** [comment]
For the next release of Debian (which is being finalized now), only `python3` is supported. `/usr/bin/python`  might exist, but it is a separate package that might go away.

**Comment by matthew-brett** [comment]
It is right to do this in the `scripts` directory?  Won't these be rewritten by installation?

**Comment by mr-c** [comment]
> I'm for dropping Python 2, but I'd rather do it as a deliberate act, e.g., set it in the classifiers and set `python_requires` so that Python 2 installations at least have a chance of not installing something that is guaranteed to break.

I recommend this checklist https://adamj.eu/tech/2019/03/13/dropping-python-2-support/

Followed by `git ls-files | grep py$ | xargs pyupgrade --py36-plus`

**Comment by matthew-brett** [comment]
Thanks - that's useful.   I think we should keep Python 2 support for this next release though - as the last release supporting Python 2.

**Comment by effigies** [comment]
If we're not breaking py2 immediately, then I'd say the cleanest way to achieve this task would be to move scripts to entrypoints, and the install process should ensure they have the right shebang. That should work, since I haven't heard complaints about nibabel scripts, and that's in neurodebian if not Debian.

**Comment by matthew-brett** [comment]
@effigies - good idea - working on that over at #476

**Pull request closed without merging**
