### PR TITLE
MRG: refactor, fix traxis build

### PR DESCRIPTION
**Pull request by matthew-brett**
Python 3 builds broken for travis - refactor using dipy as template to get
better handle on the problem.

### CODE REVIEW

**Comment by matthew-brett** [comment]
I think this one is ready to merge.  The Python 3 builds give errors, but the errors now show the real problem rather than an unrelated build problem, as we had before.

The new minimal dependency check also fails, but in a useful way, because Alexis' changes have pushed our scipy dependency up about 0.12, which needs some thought.

**Comment by matthew-brett** [comment]
Any comments here?

**Comment by bthirion** [comment]
Sorry, I don,'t understand what you want to do here. The build is broken again, even under Python 2.

**Comment by matthew-brett** [comment]
I tried to explain in the comments.

The standard Python 2 builds pass, as before.

The Python 3 builds fail, but usefully, instead of failing at the build step.

I added an extra Python 2 check against our declared minimum dependencies, which fails because of the Lapack refactor, which we are currently reviewing.

**Comment by matthew-brett** [comment]
Any comments here?   If not, I'll merge soon.

**Comment by bcipolli** [comment]
I think we need to merge this one ASAP, to better see impact on #346, #348 and subsequent PRs. The biggest change of note for me is to a minimum sympy from 0.6.6 to 0.7. 

As long as that's cool, I suggest merge so we can get down to investigating test failures in all PRs.

**Comment by matthew-brett** [comment]
I think the sympy change is correct - I had just forgotten to update that earlier.

I agree - let's merge this one to make it easier to test the rest.  I'll rebase the rest after merging in this one.

**Pull request merged**
