### PR TITLE
RF: replace == None with is None checks

### PR DESCRIPTION
**Pull request by matthew-brett**
We were getting lots of warnings about use of == None or != None. Replace all
instances of == None with "is None", != None with "is not None"

### CODE REVIEW

**Comment by satra** [comment]
LGTM

**Comment by bcipolli** [comment]
Agreed. please merge if the Travis build completes successfully!

**Comment by effigies** [comment]
The preferred style for a lot of these would be `x is not None` rather than `not x is None`.

**Comment by matthew-brett** [comment]
Chris - that's true - here I was only doing the simplest possible search and replace to see if it would work.  Should I go back through and apply that style do you think?

**Comment by effigies** [comment]
Reading through, I was assuming this was a style issue, but looking again it's warnings. If it doesn't produce warnings and would be a serious time sink, I wouldn't worry, since they produce the same byte code.

**Comment by matthew-brett** [comment]
Actually it turned out to be trivial to script with `perl -p -i -e` : - see 7ee6d24

**Comment by bcipolli** [comment]
Nice. I find extraneous warnings to be very dangerous--makes it hard to detect meaningful warnings. So glad you made the change, @matthew-brett --thanks!

**Comment by effigies** [comment]
All looks reasonable to me.

**Comment by bthirion** [comment]
LGTM

**Comment by matthew-brett** [comment]
OK - merging.

**Pull request merged**
