### PR TITLE
DRAFT: merged meson branch with windows fixes

### PR DESCRIPTION
**Pull request by matthew-brett**
Merge meson branch for testing with Windows.

Add some refactoring of temporary directories in tests.

### CODE REVIEW

**Comment by stefanv** [comment]
I don't have push access to this branch, otherwise I'd have tried the new commit.

**Comment by matthew-brett** [comment]
I merged in your changes - and I've given you push access to my repository.

FIrst I got a mesonpy error when trying to do an editable install - did you try that locally?

Now I get a directory error on building the wheel:

https://github.com/nipy/nipy/actions/runs/6336609740/job/17210017768

Any ideas?

**Comment by matthew-brett** [comment]
I've already merged #527 .  Does the editable build work for you?

**Comment by stefanv** [comment]
I meant merge into main, or start from that point, where we know things work.

I haven't tried the editable install.

**Comment by matthew-brett** [comment]
Superceded by #538 .

**Comment by matthew-brett** [comment]
Editable install does seem to work with:

```bash
pip install --no-build-isolation --editable .
```

https://meson-python.readthedocs.io/en/stable/how-to-guides/editable-installs.html

**Pull request closed without merging**
