### PR TITLE
FIX various fixes for deprecations in numpy, scipy, sphinx

### LINKED ISSUE #453: ImportError: cannot import name 'factorial' from 'scipy.misc'
it looks like there are new deprecations which cause issues in nipy imports. When running in `0.4.2`:
~~~
pip install nose mock
python -c "import nipy; nipy.test()"
~~~
I get:
~~~
ImportError: cannot import name 'factorial' from 'scipy.misc'
~~~

Which seems to be caused by:  https://scipy.github.io/devdocs/release.1.3.0.html#scipy-interpolate-changes

### LINKED ISSUE #456: numpy : No module named 'numpy.testing.decorators'
for recent version of numpy (1.18.1)

```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.12.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from nipy.algorithms.segmentation import brain_segmentation             
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-5dd8704fa93a> in <module>
----> 1 from nipy.algorithms.segmentation import brain_segmentation

~/miniconda3/envs/conda37/lib/python3.7/site-packages/nipy/__init__.py in <module>
     10                    __version__)
     11 
---> 12 from nipy.testing import Tester
     13 test = Tester().test
     14 bench = Tester().bench

~/miniconda3/envs/conda37/lib/python3.7/site-packages/nipy/testing/__init__.py in <module>
     42 bench = Tester().bench
     43 
---> 44 from . import decorators as dec
     45 
     46 # Allow failed import of nose if not now running tests

~/miniconda3/envs/conda37/lib/python3.7/site-packages/nipy/testing/decorators.py in <module>
      9 from __future__ import absolute_import
     10 
---> 11 from numpy.testing.decorators import *
     12 
     13 from nipy.utils import templates, example_data, DataError

ModuleNotFoundError: No module named 'numpy.testing.decorators'
```

### LINKED ISSUE #461: Consider pinning sympy to <1.6
The newer version of sympy (https://github.com/sympy/sympy/releases/tag/sympy-1.6) produces errors such as
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-0c165164c711> in <module>
----> 1 import nipy.modalities.fmri.hrf as hrf

~/nipy/nipy/modalities/fmri/hrf.py in <module>
    121 
    122 # Glover HRF
--> 123 _gexpr = gamma_expr(5.4, 5.2) - 0.35 * gamma_expr(10.8, 7.35)
    124 _gexpr = _gexpr / _get_sym_int(_gexpr)
    125 # The numerical function (pass times to get values)

~/nipy/nipy/modalities/fmri/hrf.py in gamma_expr(peak_location, peak_fwhm)
    105     return (
    106         coef * ((T >= 0) * (T+1.0e-14))**(shape-1)
--> 107         * sympy.exp(-(T+1.0e-14)/scale)
    108         )
    109 

TypeError: unsupported operand type(s) for *: 'GreaterThan' and 'Add'


```

### PR DESCRIPTION
**Pull request by mvdoc**
there you go @yarikoptic :-)

closes #456 
closes #445 
closes #452
closes #453 
closes #454 
closes #461

### CODE REVIEW

**Comment by yarikoptic** [comment]
FTR alternative to #457

**Comment by mvdoc** [comment]
well tests are failing for numpy testing related stuff. I'll dig into those errors

**Comment by yarikoptic** [comment]
I will not demand it here, but ideally we should centralize import of all those, so later only a single code place should need a fix

**Comment by mvdoc** [comment]
lol now hitting some wonderful python 2.7 and 3.5 idiosyncracies. I will fix them later, but @yarikoptic am I to assume that we do want to test both of those obsolete python versions? ;)

**Comment by mvdoc** [comment]
everything passes except building docs for some sphinx error unrelated to the changes here. I don't have time right now to look into that :\

**Comment by effigies** [comment]
@mvdoc Sphinx 3 had a lot of deprecations. Constraining `sphinx < 3` whereever the dependency is specified should resolve the issues.

That could also be a separate PR.

**Comment by yarikoptic** [comment]
Thank you @mvdoc !!! Very much appreciated.

**Comment by mvdoc** [comment]
@effigies that was an easy fix, thanks! however now it's failing for sympy's errors (yet another deprecation I might assume) :( 

```python
Exception occurred:

  File "/home/travis/build/nipy/nipy/venv/lib/python3.5/site-packages/nipy/algorithms/statistics/formula/formulae.py", line 270, in <module>

    class Beta(sympy.symbol.Dummy):

AttributeError: module 'sympy' has no attribute 'symbol'
```

you're welcome @yarikoptic  :-)

**Comment by effigies** [comment]
Probably. I haven't had to deal with sympy dependencies, so I don't have a sense of how quick the fix is.

**Comment by bakerhassan** [comment]
Do you have an update when this will go to production? I'm facing the issue of `ImportError: cannot import name 'factorial' from 'scipy.misc'`

**Comment by effigies** [comment]
@mvdoc It looks like `sympy.Dummy` has been valid for quite some time. Maybe just drop the `.symbol`?

**Comment by mvdoc** [comment]
well, this opened another can of worms. unfortunately I don't have bandwidth now to follow up on this.

- it looks like numpy's most recent pip-installable version uses f-strings in setup.py, thus it fails for py3.5 (but it has been fixed in master so we just need to wait https://github.com/numpy/numpy/pull/16346)
- sympy is complaining about something that I don't really know, and I can't troubleshoot at the moment :\

**Comment by sanjayankur31** [comment]
> * it looks like numpy's most recent pip-installable version uses f-strings in setup.py, thus it fails for py3.5 (but it has been fixed in master so we just need to wait [numpy/numpy#16346](https://github.com/numpy/numpy/pull/16346))

numpy 1.18.5 seems to include the f-string fix, so I *think* that particular error should go away now.

Going forward numpy 1.19 does not support py2 at all, so like lots of other tools, at some point support for py2 will be too hard a task and may need to be dropped?

**Comment by yarikoptic** [comment]
> @yarikoptic @effigies today I hit again errors related to this PR, googled the issue, and found my own PR :\

Ha ha -- welcome to my world!!! Have I told you my story of looking up for re-mapping Fn key on lenovo keyboards? ;)

Yes -- please push removal of py 3.5 -- we waited long enough for it to just reach its EOL, so I think it is safe to remove it.

**Comment by mvdoc** [comment]
ok I'm stuck. all versions in the matrix on travis **except** for the one building docs. from what I understood, numpydoc is trying to scrape the docstrings for sympy, and it fails. I tried downgrading either sympy or numpydoc and they all failed miserably. From what I've seen from sympy, they use an old fork of numpydoc that is shipped with sympy, and I guess something in sympy doesn't make numpydoc very happy. But I have no clue about how to fix this.

Any idea @yarikoptic @effigies ?

The error is the following (full trace here: https://travis-ci.com/github/mvdoc/nipy/jobs/397588628#L928)

```
Exception occurred:

  File "/home/travis/build/mvdoc/nipy/venv/lib/python3.6/site-packages/numpydoc/docscrape.py", line 324, in _parse_see_also

    raise ParseError("%s is not a item name" % line)

numpydoc.docscrape.ParseError: .separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(), is not a item name in "A mostly naive separation of a Mul or Add into arguments that are not\nare dependent on deps. To obtain as complete a separation of variables\nas possible, use a separation method first, e.g.:\n\n* separatevars() to change Mul, Add and Pow (including exp) into Mul\n* .expand(mul=True) to change Add or Mul into Add\n* .expand(log=True) to change log expr into an Add\n\nThe only non-naive thing that is done here is to respect noncommutative\nordering of variables and to always return (0, 0) for `self` of zero\nregardless of hints.\n\nFor nonzero `self`, the returned tuple (i, d) has the\nfollowing interpretation:\n\n* i will has no variable that appears in deps\n* d will either have terms that contain variables that are in deps, or\n  be equal to 0 (when self is an Add) or 1 (when self is a Mul)\n* if self is an Add then self = i + d\n* if self is a Mul then self = i*d\n* otherwise (self, S.One) or (S.One, self) is returned.\n\nTo force the expression to be treated as an Add, use the hint as_Add=True\n\nExamples\n========\n\n-- self is an Add\n\n>>> from sympy import sin, cos, exp\n>>> from sympy.abc import x, y, z\n\n>>> (x + x*y).as_independent(x)\n(0, x*y + x)\n>>> (x + x*y).as_independent(y)\n(x, x*y)\n>>> (2*x*sin(x) + y + x + z).as_independent(x)\n(y + z, 2*x*sin(x) + x)\n>>> (2*x*sin(x) + y + x + z).as_independent(x, y)\n(z, 2*x*sin(x) + x + y)\n\n-- self is a Mul\n\n>>> (x*sin(x)*cos(y)).as_independent(x)\n(cos(y), x*sin(x))\n\nnon-commutative terms cannot always be separated out when self is a Mul\n\n>>> from sympy import symbols\n>>> n1, n2, n3 = symbols('n1 n2 n3', commutative=False)\n>>> (n1 + n1*n2).as_independent(n2)\n(n1, n1*n2)\n>>> (n2*n1 + n1*n2).as_independent(n2)\n(0, n1*n2 + n2*n1)\n>>> (n1*n2*n3).as_independent(n1)\n(1, n1*n2*n3)\n>>> (n1*n2*n3).as_independent(n2)\n(n1, n2*n3)\n>>> ((x-n1)*(x-y)).as_independent(x)\n(1, (x - y)*(x - n1))\n\n-- self is anything else:\n\n>>> (sin(x)).as_independent(x)\n(1, sin(x))\n>>> (sin(x)).as_independent(y)\n(sin(x), 1)\n>>> exp(x+y).as_independent(x)\n(1, exp(x + y))\n\n-- force self to be treated as an Add:\n\n>>> (3*x).as_independent(x, as_Add=True)\n(0, 3*x)\n\n-- force self to be treated as a Mul:\n\n>>> (3+x).as_independent(x, as_Add=False)\n(1, x + 3)\n>>> (-3+x).as_independent(x, as_Add=False)\n(1, x - 3)\n\nNote how the below differs from the above in making the\nconstant on the dep term positive.\n\n>>> (y*(-3+x)).as_independent(x)\n(y, x - 3)\n\n-- use .as_independent() for true independence testing instead\n   of .has(). The former considers only symbols in the free\n   symbols while the latter considers all symbols\n\n>>> from sympy import Integral\n>>> I = Integral(x, (x, 1, 2))\n>>> I.has(x)\nTrue\n>>> x in I.free_symbols\nFalse\n>>> I.as_independent(x) == (I, 1)\nTrue\n>>> (I + x).as_independent(x) == (I, x)\nTrue\n\nNote: when trying to get independent terms, a separation method\nmight need to be used first. In this case, it is important to keep\ntrack of what you send to this routine so you know how to interpret\nthe returned values\n\n>>> from sympy import separatevars, log\n>>> separatevars(exp(x+y)).as_independent(x)\n(exp(y), exp(x))\n>>> (x + x*y).as_independent(y)\n(x, x*y)\n>>> separatevars(x + x*y).as_independent(y)\n(x, y + 1)\n>>> (x*(1 + y)).as_independent(y)\n(x, y + 1)\n>>> (x*(1 + y)).expand(mul=True).as_independent(y)\n(x, x*y)\n>>> a, b=symbols('a b', positive=True)\n>>> (log(a*b).expand(log=True)).as_independent(b)\n(log(a), log(b))\n\nSee Also\n========\n.separatevars(), .expand(log=True), sympy.core.add.Add.as_two_terms(),\nsympy.core.mul.Mul.as_two_terms(), .as_coeff_add(), .as_coeff_mul()"
```

**Comment by mvdoc** [comment]
wohoo! downgrading to an ancient numpydoc builds the docs fine.

the appveyor failures seem to be random and related to files being accessed by multiple processes. I don't think it's related at all with the code.

@yarikoptic awaiting your blessing

**Comment by mvdoc** [comment]
just pinging @yarikoptic @effigies ;)

**Comment by yarikoptic** [comment]
appveyor -- I would not completely rule out possibility of some side-effect of this PR, but 
- indeed removal of temp files on windows is a touchy topic, in datalad we do some retries and sleeping - but did have to fixup some real cases where files were not properly closed  by the end of the test
- to keep nipy going forward, I am blessing this PR to be merged, and with the power given to me pressing the button.  If anything - we will fix up ;)

**Pull request merged**
